---
title: "GKAP Analysis"
author: "Max Weiss"
date: "6/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, output = FALSE, message = FALSE, warning = FALSE)

#Library Downloads

library(tidyverse)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(stringr)
library(lubridate)
library(knitr)
library(tidytext)
library(plotly)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(readxl)

```

```{r data load and cleaning 2011}

gkap11 <- read_csv("GKAP2011_Agg.csv")

clean11 <- gkap11 %>%
  mutate(Response_Legal = Q48B, Response_Medical = Q44A) %>% #Standardize back to original values
  mutate(Coded_Legal = case_when(is.na(Coded_Legal) ~"NA",
                                 Coded_Legal == "ind. no" ~ "indeterminate unwilling",
                                 Coded_Legal == "ind. yes" ~ "indeterminate willing",
                                 Coded_Legal == "NMI" ~ "need more information",
                                 Coded_Legal == "xx" ~ "XX",
                                 Coded_Legal == "value-n: anti-government" ~ "anti-government",
                                 Coded_Legal == "value-n: DNA skepticism" ~ "DNA skepticism",
                                 Coded_Legal == "value-n: general" ~ "general",
                                 Coded_Legal == "value-n: privacy" ~ "privacy",
                                 Coded_Legal == "value-n: violates rights" ~ "violates rights",
                                 Coded_Legal == "value-y: exoneration/innocence" ~ "exoneration/innocence",
                                 Coded_Legal == "value-y: general" ~ "general",
                                 Coded_Legal == "value-y: help society" ~ "help society",
                                 Coded_Legal == "value-y: justice" ~ "justice",
                                 Coded_Legal == "value-y: obey authority" ~ "obey authority",
                                 Coded_Legal == "value-y: punishment" ~ "punishment",
                                 Coded_Legal == "value-y: research" ~ "research",
                                 Coded_Legal == "value-y: truth" ~ "truth",
                                 TRUE ~ Coded_Legal)) %>%
  mutate(Coded_Medical_A = case_when(is.na(Coded_Medical_A) ~ "NA",
                                     Coded_Medical_A == "NMI" ~ "need more information",
                                     Coded_Medical_A == "CONDITIONAL TRUST" ~ "need more information",
                                     Coded_Medical_A == "INTEREST-NO" ~ "interest",
                                     Coded_Medical_A == "INTEREST-YES" ~ "interest",
                                     Coded_Medical_A == "MEDICAL CIRE" ~ "medical cure",
                                     Coded_Medical_A == "MEDICAL CURE" ~ "medical cure",
                                     Coded_Medical_A == "MEDICAL CURES-YES" ~ "medical cure",
                                     Coded_Medical_A == "MEDICAL CURES-YES" ~ "medical cure",
                                     Coded_Medical_A == "MEDICAL KNOWLEDGE-YES" ~ "medical cure",
                                     Coded_Medical_A == "MEDICAL RESEARCH" ~ "medical cure",
                                     Coded_Medical_A == "MEDICICAL CURE" ~ "medical cure",
                                     Coded_Medical_A == "MEDICSL CURE" ~ "medical cure",
                                     Coded_Medical_A == "MEDICSL CURE" ~ "medical cure",
                                     Coded_Medical_A == "MEDUCAL CURE" ~ "medical cure",
                                     Coded_Medical_A == "SCIENTIFIC CURE" ~ "medical cure",
                                     Coded_Medical_A == "MISTRUST" ~ "mistrust",
                                     Coded_Medical_A == "NMI-NO" ~ "need more information",
                                     Coded_Medical_A == "NMI-YES" ~ "need more information",
                                     Coded_Medical_A == "PRIVACY-NO" ~ "privacy",
                                     Coded_Medical_A == "PRIVACY-YES" ~ "privacy",
                                     Coded_Medical_A == "SAMPLING-NO" ~ "sampling",
                                     Coded_Medical_A == "SAMPLING-YES" ~ "sampling",
                                     Coded_Medical_A == "PRIVACY-NO" ~ "privacy",
                                     Coded_Medical_A == "SCIENTIFIC KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCEINTIFIC KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTFIC  KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTFIC KNOWLEDG" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTFICI KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIF KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFC KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFI KNOWLEDG" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFI KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KN" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNOLWEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNOWLDEGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNOWLEDE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNOWLEDEGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNOWLEDG" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNOWLEDHE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNOWLEGES" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC KNWOLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTIFIC NOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCIENTITIC KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "SCINTIFIC KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_A == "TRUST" ~ "trust",
                                     Coded_Medical_A == "TRUST/MISTRUST" & Response_Medical %in% c(1,2) ~ "trust",
                                     Coded_Medical_A == "TRUST/MISTRUST" & Response_Medical %in% c(3,4,5) ~ "mistrust",
                                     Coded_Medical_A == "VALUE" ~ "value",
                                     Coded_Medical_A == "VALUE-YES" ~ "value",
                                     Coded_Medical_A == "VALUE-NO" ~ "value",
                                     Coded_Medical_A == 5 ~ "XX",
                                     Coded_Medical_A == 16 ~ "XX",
                                     Coded_Medical_A == 14 ~ "XX",
                                     TRUE ~ Coded_Medical_A)) %>%
  mutate(Coded_Medical_B = case_when(Coded_Medical_B == "NMI" ~ "need more information",
                                     Coded_Medical_B == "CONDITIONAL TRUST" ~ "need more information",
                                     Coded_Medical_B == "INTEREST-NO" ~ "interest",
                                     Coded_Medical_B == "INTEREST-YES" ~ "interest",
                                     Coded_Medical_B == "MEDICAL CURE" ~ "medical cure",
                                     Coded_Medical_B == "MISTRUST" ~ "mistrust",
                                     Coded_Medical_B == "NMI-NO" ~ "need more information",
                                     Coded_Medical_B == "NMI-YES" ~ "need more information",
                                     Coded_Medical_B == "PRIVACY-NO" ~ "privacy",
                                     Coded_Medical_B == "PRIVACY-YES" ~ "privacy",
                                     Coded_Medical_B == "SAMPLING-YES" ~ "sampling",
                                     Coded_Medical_B == "SCIENTIFIC KNOWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_B == "SCIENTIFIC KNWLEDGE" ~ "scientific knowledge",
                                     Coded_Medical_B == "TRUST" ~ "trust",
                                     Coded_Medical_B == "TRUST/MISTRUST" & Response_Medical %in% c(1,2) ~ "trust",
                                     Coded_Medical_B == "TRUST/MISTRUST" & Response_Medical %in% c(3,4,5) ~ "mistrust",
                                     Coded_Medical_B == "VALUE-YES" ~ "value",
                                     Coded_Medical_B == "VALUE-NO" ~ "value",
                                     Coded_Medical_B == "5" ~ "XX",
                                     Coded_Medical_B == 5 ~ "XX",
                                     Coded_Medical_B == 16 ~ "XX",
                                     Coded_Medical_B == 14 ~ "XX",
                                     TRUE ~ Coded_Medical_B))
  
gather11 <- clean11 %>%
  gather(Coded_Medical_A, Coded_Medical_B, key = "Coded_Medical_AB", value = "Coded_Medical") %>%
  filter(!is.na(Coded_Medical)) %>%
  select(X1, CaseID, Response_Legal, OpenEnd_Legal, Coded_Legal, Response_Medical, OpenEnd_Medical, Coded_Medical_AB, Coded_Medical, weight1:pppa0012) %>%
  arrange(CaseID)

clean11 %>% write_csv("GKAP2011_Clean.csv")
gather11 %>% write_csv("GKAP2011_Split.csv")

```


```{r data load and cleaning 2017}

gkap17 <- read_csv("GKAP2017_Agg.csv")

clean17 <- gkap17 %>%
  mutate(Coded_Legal = case_when(is.na(Coded_Legal) ~"NA",
                                 Coded_Legal == "Na" ~"NA",
                                 Coded_Legal == "na" ~"NA",
                                 Coded_Legal == "ind. no" ~ "indeterminate unwilling",
                                 Coded_Legal == "ind. yes" ~ "indeterminate willing",
                                 Coded_Legal == "NMI" ~ "need more information",
                                 Coded_Legal == "xx" ~ "XX",
                                 Coded_Legal == "value-n: anti-government" ~ "anti-government",
                                 Coded_Legal == "value-n: DNA skepticism" ~ "DNA skepticism",
                                 Coded_Legal == "value-n: general" ~ "general",
                                 Coded_Legal == "value-n: privacy" ~ "privacy",
                                 Coded_Legal == "value-n: violates rights" ~ "violates rights",
                                 Coded_Legal == "value-y: exoneration/innocence" ~ "exoneration/innocence",
                                 Coded_Legal == "value-y: general" ~ "general",
                                 Coded_Legal == "value-y: help society" ~ "help society",
                                 Coded_Legal == "value-y: justice" ~ "justice",
                                 Coded_Legal == "value-y: obey authority" ~ "obey authority",
                                 Coded_Legal == "value-y: punishment" ~ "punishment",
                                 Coded_Legal == "value-y: research" ~ "research",
                                 Coded_Legal == "value-y: truth" ~ "truth",
                                 TRUE ~ Coded_Legal)) %>%
  mutate(Coded_Medical_A = case_when(is.na(Coded_Medical_A) ~ "NA",
                                 Coded_Medical_A == "conditional trust" ~ "need more information",
                                 Coded_Medical_A == "conditional mistrust" ~ "need more information",
                                 TRUE ~ Coded_Medical_A)) %>%
  mutate(Coded_Medical_B = case_when(Coded_Medical_B == "conditional trust" ~ "need more information",
                                 Coded_Medical_B == "conditional mistrust" ~ "need more information",
                                 TRUE ~ Coded_Medical_B))

gather17 <- clean17 %>%
  gather(Coded_Medical_A, Coded_Medical_B, key = "Coded_Medical_AB", value = "Coded_Medical") %>%
  filter(!is.na(Coded_Medical)) %>%
  select(X1, CaseID, Response_Legal, OpenEnd_Legal, Coded_Legal, Response_Medical, OpenEnd_Medical, Coded_Medical_AB, Coded_Medical, weight1:pppa1690) %>%
  arrange(CaseID)

clean17 %>% write_csv("GKAP2017_Clean.csv")
gather17 %>% write_csv("GKAP2017_Split.csv")

```

```{r Summary}

#How Many Respondents?

respondents17 <- clean17 %>%
  summarize("Respondents" = n())

respondents11 <- clean11 %>%
  summarize("Respondents" = n())

```

##Summary

* Number of Respondents
    + 2011: `r respondents11`
    + 2017: `r respondents17`


```{r Summary Favorability}

#LEGAL QUESTION 2017:
#Would you be willing or unwilling to contribute a DNA sample, for example by a swab from
#your mouth, for use in current or future investigations to determine a person’s guilt or
#innocence of a particular crime?

#MEDICAL QUESTION 2017:
#Would you be willing or unwilling to contribute a DNA sample, for example by a swab from
#your mouth, for use in current or future scientific or medical research?

cat11 <- clean11 %>%
  mutate(Response_Legal = case_when(Response_Legal == 1 ~ "Willing",
                                    Response_Legal == 2 ~ "Somewhat willing",
                                    Response_Legal == 3 ~ "Somewhat unwilling",
                                    Response_Legal == 4 ~ "Unwilling",
                                    Response_Legal == -1 ~ "REFUSED")) %>%
  mutate(Response_Medical = case_when(Response_Medical == 1 ~ "Willing",
                                    Response_Medical == 2 ~ "Somewhat willing",
                                    Response_Medical == 3 ~ "Somewhat unwilling",
                                    Response_Medical == 4 ~ "Unwilling",
                                    Response_Medical == -1 ~ "REFUSED"))

#LEGAL QUESTION 2017:
#Would you be willing or unwilling to contribute a DNA sample, for example by a swab from
#your mouth, for use in current or future investigations to determine a person’s guilt or
#innocence of a particular crime?

#MEDICAL QUESTION 2017:
#Would you be willing or unwilling to contribute a DNA sample, for example by a swab from
#your mouth, for use in current or future scientific or medical research?

cat17 <- clean17 %>%
  mutate(Response_Legal = case_when(Response_Legal == 1 ~ "Willing",
                                    Response_Legal == 2 ~ "Somewhat willing",
                                    Response_Legal == 3 ~ "Somewhat unwilling",
                                    Response_Legal == 4 ~ "Unwilling",
                                    Response_Legal == -1 ~ "REFUSED")) %>%
  mutate(Response_Medical = case_when(Response_Medical == 1 ~ "Willing",
                                    Response_Medical == 2 ~ "Somewhat willing",
                                    Response_Medical == 3 ~ "Somewhat unwilling",
                                    Response_Medical == 4 ~ "Unwilling",
                                    Response_Medical == -1 ~ "REFUSED"))

cat11 %>%
  gather(Response_Legal, Response_Medical, key = "Type", value = "Favorability") %>%
  group_by(Type) %>%
  count(Favorability) %>%
  mutate(Favorability = fct_relevel(Favorability, "Willing", "Somewhat willing", "Somewhat unwilling", "Unwilling", "REFUSED")) %>%
  ggplot(aes(x = Favorability, y = n, fill = Type)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

cat17 %>%
  gather(Response_Legal, Response_Medical, key = "Type", value = "Favorability") %>%
  group_by(Type) %>%
  count(Favorability) %>%
  mutate(Favorability = fct_relevel(Favorability, "Willing", "Somewhat willing", "Somewhat unwilling", "Unwilling", "REFUSED")) %>%
  ggplot(aes(x = Favorability, y = n, fill = Type)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#Average Favorabilities

calc11 <- clean11 %>%
  mutate(Response_Legal = case_when(Response_Legal == 1 ~ '3',
                                    Response_Legal == 2 ~ '2',
                                    Response_Legal == 3 ~ '1',
                                    Response_Legal == 4 ~ '0',
                                    Response_Legal == -1 ~ NA_character_)) %>%
  mutate(Response_Legal = parse_integer(Response_Legal)) %>%
  mutate(Response_Medical = case_when(Response_Medical == 1 ~ '3',
                                    Response_Medical == 2 ~ '2',
                                    Response_Medical == 3 ~ '1',
                                    Response_Medical == 4 ~ '0',
                                    Response_Medical == -1 ~ NA_character_)) %>%
  mutate(Response_Medical = parse_integer(Response_Medical))
  

calc17 <- clean17 %>%
  mutate(Response_Legal = case_when(Response_Legal == 1 ~ '3',
                                    Response_Legal == 2 ~ '2',
                                    Response_Legal == 3 ~ '1',
                                    Response_Legal == 4 ~ '0',
                                    Response_Legal == -1 ~ NA_character_)) %>%
  mutate(Response_Legal = parse_integer(Response_Legal)) %>%
  mutate(Response_Medical = case_when(Response_Medical == 1 ~ '3',
                                    Response_Medical == 2 ~ '2',
                                    Response_Medical == 3 ~ '1',
                                    Response_Medical == 4 ~ '0',
                                    Response_Medical == -1 ~ NA_character_)) %>%
  mutate(Response_Medical = parse_integer(Response_Medical))

calc11 %>%
  summarise(Legal_Favorability = mean(Response_Legal, na.rm = TRUE), 
            Medical_Favorability = mean(Response_Medical, na.rm = TRUE), 
            sd_leg = sd(Response_Legal, na.rm = TRUE),
            se_leg = 1.96 * sd_leg/sqrt(n()),
            sd_med = sd(Response_Medical, na.rm = TRUE),
            se_med = 1.96 * sd_med/sqrt(n())) %>%
  gather(Legal_Favorability, Medical_Favorability, key = "Type", value = "Favorability") %>%
  mutate(se = ifelse(Type == "Legal_Favorability", se_leg, se_med)) %>%
  select(Type, Favorability, se) %>%
  ggplot(aes(x = Type, y = Favorability)) +
  geom_col(position = "dodge", fill = "royalblue4") +
  geom_errorbar(aes(ymin = Favorability - se, ymax = Favorability + se), width=.4) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Favorability Score Med vs. Legal 2011", caption = "CAPTION CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

calc17 %>%
  summarise(Legal_Favorability = mean(Response_Legal, na.rm = TRUE), 
            Medical_Favorability = mean(Response_Medical, na.rm = TRUE), 
            sd_leg = sd(Response_Legal, na.rm = TRUE),
            se_leg = 1.96 * sd_leg/sqrt(n()),
            sd_med = sd(Response_Medical, na.rm = TRUE),
            se_med = 1.96 * sd_med/sqrt(n())) %>%
  gather(Legal_Favorability, Medical_Favorability, key = "Type", value = "Favorability") %>%
  mutate(se = ifelse(Type == "Legal_Favorability", se_leg, se_med)) %>%
  select(Type, Favorability, se) %>%
  ggplot(aes(x = Type, y = Favorability)) +
  geom_col(position = "dodge", fill = "royalblue4") +
  geom_errorbar(aes(ymin = Favorability - se, ymax = Favorability + se), width=.4) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Favorability Score Med vs. Legal 2017", caption = "CAPTION CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))



calc11_2 <- calc11 %>%
  summarise(Legal_Favorability = mean(Response_Legal, na.rm = TRUE), 
            Medical_Favorability = mean(Response_Medical, na.rm = TRUE), 
            sd_leg = sd(Response_Legal, na.rm = TRUE),
            se_leg = 1.96 * sd_leg/sqrt(n()),
            sd_med = sd(Response_Medical, na.rm = TRUE),
            se_med = 1.96 * sd_med/sqrt(n())) %>%
  gather(Legal_Favorability, Medical_Favorability, key = "Type", value = "Favorability") %>%
  mutate(se = ifelse(Type == "Legal_Favorability", se_leg, se_med), Year = '2011') %>%
  select(Type, Favorability, se, Year)

calc17 %>%
  summarise(Legal_Favorability = mean(Response_Legal, na.rm = TRUE), 
            Medical_Favorability = mean(Response_Medical, na.rm = TRUE), 
            sd_leg = sd(Response_Legal, na.rm = TRUE),
            se_leg = 1.96 * sd_leg/sqrt(n()),
            sd_med = sd(Response_Medical, na.rm = TRUE),
            se_med = 1.96 * sd_med/sqrt(n())) %>%
  gather(Legal_Favorability, Medical_Favorability, key = "Type", value = "Favorability") %>%
  mutate(se = ifelse(Type == "Legal_Favorability", se_leg, se_med), Year = '2017') %>%
  select(Type, Favorability, se, Year) %>%
  bind_rows(calc11_2) %>%
  ggplot(aes(x = Type, y = Favorability, fill = Year)) +
  geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = Favorability - se, ymax = Favorability + se), width= .9, position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Favorability Score Med vs. Legal 2011/2017", caption = "CAPTION CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))
  

```

```{r Open End Analysis}

#Legal Open End Classifications

leg11 <- clean11 %>%
  select(X1:Coded_Medical_B) %>%
  mutate(Year = '2011')
  

leg17 <- clean17 %>% 
  select(X1:Coded_Medical_B) %>%
  mutate(Year = '2017')

leg11 %>%
  bind_rows(leg17) %>%
  group_by(Year) %>%
  count(Coded_Legal) %>%
  filter(Coded_Legal != "NA", Coded_Legal != "XX") %>%
  mutate(`Relative Frequency` = n/sum(n)) %>%
  ggplot(aes(x = Coded_Legal, y = `Relative Frequency`, fill = Year)) +
  geom_col(position = 'dodge') +
  ylab("Relative Frequencies") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Frequency of Open-Ended Response Classifications (ADJUSTED)")


#Medical Open End Classifications

label11 <- gather11 %>%
  select(X1:Coded_Medical) %>%
  mutate(Year = '2011')
  

label17 <- gather17 %>% 
  select(X1:Coded_Medical) %>%
  mutate(Year = '2017')

label11 %>%
  bind_rows(label17) %>%
  group_by(Year) %>%
  count(Coded_Medical) %>%
  filter(Coded_Medical != "NA", Coded_Medical != "XX") %>%
  mutate(`Relative Frequency` = n/sum(n)) %>%
  ggplot(aes(x = Coded_Medical, y = `Relative Frequency`, fill = Year)) +
  geom_col(position = 'dodge') +
  ylab("Relative Frequencies") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Frequency of Open-Ended Response Classifications (ADJUSTED)")


#Average Favorability by Class

calc11 %>%
  filter(Coded_Legal != "NA", Coded_Legal != "XX") %>%
  group_by(Coded_Legal) %>%
  summarise(Favorability = mean(Response_Legal, na.rm = TRUE), 
            sd = sd(Response_Legal, na.rm = TRUE),
            se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = Coded_Legal, y = Favorability)) +
  geom_col(position = "dodge", fill = "royalblue4") +
  geom_errorbar(aes(ymin = Favorability - se, ymax = Favorability + se), width=.4) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Favorability Score Legal 2011", caption = "CAPTION CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

calc17 %>%
  filter(Coded_Legal != "NA", Coded_Legal != "XX") %>%
  group_by(Coded_Legal) %>%
  summarise(Favorability = mean(Response_Legal, na.rm = TRUE), 
            sd = sd(Response_Legal, na.rm = TRUE),
            se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = Coded_Legal, y = Favorability)) +
  geom_col(position = "dodge", fill = "royalblue4") +
  geom_errorbar(aes(ymin = Favorability - se, ymax = Favorability + se), width=.4) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Favorability Score Legal 2017", caption = "CAPTION CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))


gather11_2 <- gather11 %>%
  mutate(Response_Legal = case_when(Response_Legal == 1 ~ '3',
                                    Response_Legal == 2 ~ '2',
                                    Response_Legal == 3 ~ '1',
                                    Response_Legal == 4 ~ '0',
                                    Response_Legal == -1 ~ NA_character_)) %>%
  mutate(Response_Legal = parse_integer(Response_Legal)) %>%
  mutate(Response_Medical = case_when(Response_Medical == 1 ~ '3',
                                    Response_Medical == 2 ~ '2',
                                    Response_Medical == 3 ~ '1',
                                    Response_Medical == 4 ~ '0',
                                    Response_Medical == -1 ~ NA_character_)) %>%
  mutate(Response_Medical = parse_integer(Response_Medical))

gather17_2 <- gather17 %>%
  mutate(Response_Legal = case_when(Response_Legal == 1 ~ '3',
                                    Response_Legal == 2 ~ '2',
                                    Response_Legal == 3 ~ '1',
                                    Response_Legal == 4 ~ '0',
                                    Response_Legal == -1 ~ NA_character_)) %>%
  mutate(Response_Legal = parse_integer(Response_Legal)) %>%
  mutate(Response_Medical = case_when(Response_Medical == 1 ~ '3',
                                    Response_Medical == 2 ~ '2',
                                    Response_Medical == 3 ~ '1',
                                    Response_Medical == 4 ~ '0',
                                    Response_Medical == -1 ~ NA_character_)) %>%
  mutate(Response_Medical = parse_integer(Response_Medical))

gather11_2 %>%
  filter(Coded_Medical != "NA", Coded_Medical != "XX") %>%
  group_by(Coded_Medical) %>%
  summarise(Favorability = mean(Response_Medical, na.rm = TRUE), 
            sd = sd(Response_Medical, na.rm = TRUE),
            se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = Coded_Medical, y = Favorability)) +
  geom_col(position = "dodge", fill = "royalblue4") +
  geom_errorbar(aes(ymin = Favorability - se, ymax = Favorability + se), width=.4) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Favorability Score Medical 2011", caption = "CAPTION CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

gather17_2 %>%
  filter(Coded_Medical != "NA", Coded_Medical != "XX") %>%
  group_by(Coded_Medical) %>%
  summarise(Favorability = mean(Response_Medical, na.rm = TRUE), 
            sd = sd(Response_Medical, na.rm = TRUE),
            se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = Coded_Medical, y = Favorability)) +
  geom_col(position = "dodge", fill = "royalblue4") +
  geom_errorbar(aes(ymin = Favorability - se, ymax = Favorability + se), width=.4) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Favorability Score Medical 2017", caption = "CAPTION CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))


```


```{r Build Aggregate Dataset}

agg11 <- calc11 %>%
  mutate(Year = '2011') %>%
  mutate(party = pppa0012) %>%
  rename_all(toupper)
  
agg <- calc17 %>% 
  mutate(Year = '2017') %>%
  mutate(party = ppp10012) %>%
  rename_all(toupper) %>%
  bind_rows(agg11)

agg %>% select()

```


```{r POLITICS}
#Average Favorability Score by Political Ideology

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  filter(PARTY != -1, PARTY != -2) %>%
  mutate(PARTY = case_when(PARTY == 1 ~ "1 - Extremely Liberal", 
                           PARTY == 7 ~ "7 - Extremely Conservative",
                           TRUE ~ as.character(PARTY))) %>%
  group_by(PARTY, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PARTY, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Political Ideology", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  filter(PARTY != -1, PARTY != -2) %>%
  mutate(PARTY = case_when(PARTY == 1 ~ "1 - Extremely Liberal", 
                           PARTY == 7 ~ "7 - Extremely Conservative",
                           TRUE ~ as.character(PARTY))) %>%
  group_by(PARTY, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PARTY, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Political Ideology", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))


#Average Favorability Score by Party ID

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  filter(PARTYID7 != -1, PARTYID7 != -2) %>%
  mutate(PARTYID7 = case_when(PARTYID7 == 1 ~ "1 - Strongly Republican", 
                           PARTYID7 == 7 ~ "7 - Strongly Democrat",
                           TRUE ~ as.character(PARTYID7))) %>%
  group_by(PARTYID7, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PARTYID7, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Party ID", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  filter(PARTYID7 != -1, PARTYID7 != -2) %>%
  mutate(PARTYID7 = case_when(PARTYID7 == 1 ~ "1 - Strongly Republican", 
                           PARTYID7 == 7 ~ "7 - Strongly Democrat",
                           TRUE ~ as.character(PARTYID7))) %>%
  group_by(PARTYID7, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PARTYID7, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Party ID", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))


#Average Favorability Score by Candidate

#MEDICAL 2017
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  filter(PPPA1690 %in% c(1, 2)) %>%
  mutate(PPPA1690 = case_when(PPPA1690 == 1 ~ "Clinton", 
                           PPPA1690 == 2 ~ "Trump")) %>%
  group_by(PPPA1690, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPPA1690, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Candidate 2017", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL 2017
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  filter(PPPA1690 %in% c(1, 2)) %>%
  mutate(PPPA1690 = case_when(PPPA1690 == 1 ~ "Clinton", 
                           PPPA1690 == 2 ~ "Trump")) %>%
  group_by(PPPA1690, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPPA1690, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Candidate 2017", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

```

```{r RACE/ETHNICITY}

#Average Favorability Score by Race/Ethnicity

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  mutate(PPETHM = case_when(PPETHM == 1 ~ "White, Non-Hispanic", 
                            PPETHM == 2 ~ "Black, Non-Hispanic", 
                            PPETHM == 3 ~ "Other, Non-Hispanic", 
                            PPETHM == 4 ~ "Hispanic",
                            PPETHM == 5 ~ "2+ Races, Non-Hispanic")) %>%
  group_by(PPETHM, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPETHM, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Ethnicity", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  mutate(PPETHM = case_when(PPETHM == 1 ~ "White, Non-Hispanic", 
                            PPETHM == 2 ~ "Black, Non-Hispanic", 
                            PPETHM == 3 ~ "Other, Non-Hispanic", 
                            PPETHM == 4 ~ "Hispanic",
                            PPETHM == 5 ~ "2+ Races, Non-Hispanic")) %>%
  group_by(PPETHM, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPETHM, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Ethnicity", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

```

```{r AGE}

#Average Favorability Score by AGE

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  ggplot(aes(x = PPAGE, y = RESPONSE_LEGAL)) +
  geom_jitter(alpha = .8) +
  geom_smooth(method = 'lm', se = FALSE) +
  geom_smooth(aes(color = "red")) +
  facet_grid(~YEAR) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Age", caption = "") +
  ylab("Average Favorability") +
  xlab("Age")

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  ggplot(aes(x = PPAGE, y = RESPONSE_LEGAL)) +
  geom_jitter(alpha = .8) +
  geom_smooth(method = 'lm', se = FALSE) +
  geom_smooth(aes(color = "red")) +
  facet_grid(~YEAR) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Age", caption = "") +
  ylab("Average Favorability") +
  xlab("Age")


#Average Favorability Score by Age

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  mutate(PPAGECAT = case_when(PPAGECAT == 1 ~ "18-24", 
                           PPAGECAT == 2 ~ "25-34", 
                           PPAGECAT == 3 ~ "35-44",
                           PPAGECAT == 4 ~ "45-54",
                           PPAGECAT == 5 ~ "55-64",
                           PPAGECAT == 6 ~ "65-74",
                           PPAGECAT == 7 ~ "75+")) %>%
  group_by(PPAGECAT, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPAGECAT, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Age", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  mutate(PPAGECAT = case_when(PPAGECAT == 1 ~ "18-24", 
                           PPAGECAT == 2 ~ "25-34", 
                           PPAGECAT == 3 ~ "35-44",
                           PPAGECAT == 4 ~ "45-54",
                           PPAGECAT == 5 ~ "55-64",
                           PPAGECAT == 6 ~ "65-74",
                           PPAGECAT == 7 ~ "75+")) %>%
  group_by(PPAGECAT, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPAGECAT, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Age", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))


```

```{r GENDER}

#Average Favorability Score by GENDER

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  mutate(PPGENDER = case_when(PPGENDER == 1 ~ "Male", 
                           PPGENDER == 2 ~ "Female")) %>%
  group_by(PPGENDER, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPGENDER, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Gender", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  mutate(PPGENDER = case_when(PPGENDER == 1 ~ "Male", 
                           PPGENDER == 2 ~ "Female")) %>%
  group_by(PPGENDER, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPGENDER, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Gender", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

```

```{r INCOME}

#Average Favorability Score by INCOME

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  mutate(PPINCIMP = case_when(PPINCIMP == 1 ~ 'Less than $5,000',
                              PPINCIMP == 2 ~ '$5,000 to $7,499',
                              PPINCIMP == 3 ~ '$7,500 to $9,999',
                              PPINCIMP == 4 ~ '$10,000 to $12,499',
                              PPINCIMP == 5 ~ '$12,500 to $14,999',
                              PPINCIMP == 6 ~ '$15,000 to $19,999',
                              PPINCIMP == 7 ~ '$20,000 to $24,999',
                              PPINCIMP == 8 ~ '$25,000 to $29,999',
                              PPINCIMP == 9 ~ '$30,000 to $34,999',
                              PPINCIMP == 10 ~ '$35,000 to $39,999',
                              PPINCIMP == 11 ~ '$40,000 to $49,999',
                              PPINCIMP == 12 ~ '$50,000 to $59,999',
                              PPINCIMP == 13 ~ '$60,000 to $74,999',
                              PPINCIMP == 14 ~ '$75,000 to $84,999',
                              PPINCIMP == 15 ~ '$85,000 to $99,999',
                              PPINCIMP == 16 ~ '$100,000 to $124,999',
                              PPINCIMP == 17 ~ '$125,000 to $149,999',
                              PPINCIMP == 18 ~ '$150,000 to $174,999',
                              PPINCIMP == 19 ~ '$175,000 to $199,999',
                              PPINCIMP == 20 ~ '$175,000 to $199,999',
                              PPINCIMP == 21 ~ '$175,000 to $199,999')) %>%
    mutate(PPINCIMP = fct_relevel(PPINCIMP, 'Less than $5,000',
                                          '$5,000 to $7,499',
                                          '$7,500 to $9,999',
                                          '$10,000 to $12,499',
                                          '$12,500 to $14,999',
                                          '$15,000 to $19,999',
                                          '$20,000 to $24,999',
                                          '$25,000 to $29,999',
                                          '$30,000 to $34,999',
                                          '$35,000 to $39,999',
                                          '$40,000 to $49,999',
                                          '$50,000 to $59,999',
                                          '$60,000 to $74,999',
                                          '$75,000 to $84,999',
                                          '$85,000 to $99,999',
                                          '$100,000 to $124,999',
                                          '$125,000 to $149,999',
                                          '$150,000 to $174,999',
                                          '$175,000 to $199,999')) %>%
  group_by(PPINCIMP, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPINCIMP, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Income", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  mutate(PPINCIMP = case_when(PPINCIMP == 1 ~ 'Less than $5,000',
                              PPINCIMP == 2 ~ '$5,000 to $7,499',
                              PPINCIMP == 3 ~ '$7,500 to $9,999',
                              PPINCIMP == 4 ~ '$10,000 to $12,499',
                              PPINCIMP == 5 ~ '$12,500 to $14,999',
                              PPINCIMP == 6 ~ '$15,000 to $19,999',
                              PPINCIMP == 7 ~ '$20,000 to $24,999',
                              PPINCIMP == 8 ~ '$25,000 to $29,999',
                              PPINCIMP == 9 ~ '$30,000 to $34,999',
                              PPINCIMP == 10 ~ '$35,000 to $39,999',
                              PPINCIMP == 11 ~ '$40,000 to $49,999',
                              PPINCIMP == 12 ~ '$50,000 to $59,999',
                              PPINCIMP == 13 ~ '$60,000 to $74,999',
                              PPINCIMP == 14 ~ '$75,000 to $84,999',
                              PPINCIMP == 15 ~ '$85,000 to $99,999',
                              PPINCIMP == 16 ~ '$100,000 to $124,999',
                              PPINCIMP == 17 ~ '$125,000 to $149,999',
                              PPINCIMP == 18 ~ '$150,000 to $174,999',
                              PPINCIMP == 19 ~ '$175,000 to $199,999',
                              PPINCIMP == 20 ~ '$175,000 to $199,999',
                              PPINCIMP == 21 ~ '$175,000 to $199,999')) %>%
  mutate(PPINCIMP = fct_relevel(PPINCIMP, 'Less than $5,000',
                                          '$5,000 to $7,499',
                                          '$7,500 to $9,999',
                                          '$10,000 to $12,499',
                                          '$12,500 to $14,999',
                                          '$15,000 to $19,999',
                                          '$20,000 to $24,999',
                                          '$25,000 to $29,999',
                                          '$30,000 to $34,999',
                                          '$35,000 to $39,999',
                                          '$40,000 to $49,999',
                                          '$50,000 to $59,999',
                                          '$60,000 to $74,999',
                                          '$75,000 to $84,999',
                                          '$85,000 to $99,999',
                                          '$100,000 to $124,999',
                                          '$125,000 to $149,999',
                                          '$150,000 to $174,999',
                                          '$175,000 to $199,999')) %>%
  group_by(PPINCIMP, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPINCIMP, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Income", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

```


```{r EDUCATION}

#Average Favorability Score by EDUCATION

#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  mutate(PPEDUCAT = case_when(PPEDUCAT == 1 ~ "Less than High School", 
                           PPEDUCAT == 2 ~ "High School", 
                           PPEDUCAT == 3 ~ "Some College",
                           PPEDUCAT == 4 ~ "Bachelor's Degree or Higher")) %>%
  mutate(PPEDUCAT = fct_relevel(PPEDUCAT, "Less than High School", 
                                          "High School", 
                                          "Some College",
                                          "Bachelor's Degree or Higher")) %>%
  group_by(PPEDUCAT, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPEDUCAT, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Education", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  mutate(PPEDUCAT = case_when(PPEDUCAT == 1 ~ "Less than High School", 
                           PPEDUCAT == 2 ~ "High School", 
                           PPEDUCAT == 3 ~ "Some College",
                           PPEDUCAT == 4 ~ "Bachelor's Degree or Higher")) %>%
  mutate(PPEDUCAT = fct_relevel(PPEDUCAT, "Less than High School", 
                                          "High School", 
                                          "Some College",
                                          "Bachelor's Degree or Higher")) %>%
  group_by(PPEDUCAT, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPEDUCAT, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Education", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))



#MEDICAL
agg %>%
  filter(!is.na(RESPONSE_MEDICAL)) %>%
  mutate(PPEDUC = case_when(PPEDUC %in% c(1:8) ~ "1 - Less than High School", 
                           PPEDUC == 9 ~ "2 - High School", 
                           PPEDUC == 10 ~ "3 - Some College",
                           PPEDUC == 11 ~ "4 - Associate Degree",
                           PPEDUC == 12 ~ "5 - Bachelor's Degree",
                           PPEDUC == 13 ~ "6 - Master's Degree",
                           PPEDUC == 14 ~ "7 - Professional Degree")) %>%
  group_by(PPEDUC, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_MEDICAL), sd = sd(RESPONSE_MEDICAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPEDUC, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Medical Favorability Score by Education", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

#LEGAL
agg %>%
  filter(!is.na(RESPONSE_LEGAL)) %>%
  mutate(PPEDUC = case_when(PPEDUC %in% c(1:8) ~ "1 - Less than High School", 
                           PPEDUC == 9 ~ "2 - High School", 
                           PPEDUC == 10 ~ "3 - Some College",
                           PPEDUC == 11 ~ "4 - Associate Degree",
                           PPEDUC == 12 ~ "5 - Bachelor's Degree",
                           PPEDUC == 13 ~ "6 - Master's Degree",
                           PPEDUC == 14 ~ "7 - Professional Degree")) %>%
  group_by(PPEDUC, YEAR) %>%
  summarise(`Average Favorability` = mean(RESPONSE_LEGAL), sd = sd(RESPONSE_LEGAL), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPEDUC, y = `Average Favorability`)) +
  geom_col() +
  facet_grid(~YEAR) +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Legal Favorability Score by Education", caption = "CAPTION CAPTION") +
  scale_y_continuous(name = "Average Favorability", limits = c(0, 3), breaks = seq(0, 3, length.out = 7))

```

