---
title: "Open Ended Medical Responses"
author: "Max Weiss"
date: "11/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, output = FALSE)

#Library Downloads

library(tidyverse)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(stringr)
library(lubridate)
library(knitr)
library(tidytext)
library(plotly)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(readxl)

```

```{r data load in}

final <- read_xlsx("~/Desktop/Genomic/Medical_OpenEnds_Final.xlsx")
split <- read_xlsx("~/Desktop/Genomic/Medical_OpenEnds_Final_Split.xlsx")

final_legal <- read_xlsx("~/Desktop/Genomic/Legal_OpenEnds_Final.xlsx")
split_legal <- read_xlsx("~/Desktop/Genomic/Legal_OpenEnds_Final_Split.xlsx")

full <- read_csv("~/Desktop/Genomic/GKAP2_FULL.csv")


final_con <- final %>%
  mutate(`Disagree with both:` = case_when(`Disagree with both:` %in% c("diasagreement", "disagreemet", "disagrement", "disasgreement") ~ "disagreement", 
                                   `Disagree with both:` == "X" ~ "disagreement",
                                   TRUE ~ `Disagree with both:`)) %>%
  mutate(med_resp = Q44a1, med_class1 = `Final 1st:`, med_class2 = `Final 2nd:`) %>%
  select(CaseID, med_resp, med_class1, med_class2)

final_con_legal <- final_legal %>%
  mutate(leg_resp = Q48b1, leg_class1 = `Final 1st:`, leg_class2 = `Final 2nd:`) %>%
  select(CaseID, leg_resp, leg_class1, leg_class2)

full_wmed <- left_join(final_con, full, by = "CaseID")
full_full <- left_join(final_con_legal, full_wmed, by = "CaseID")

```

```{r Summary}

#How Many Respondents?

full_full %>%
  summarize("Number of Samples" = n())

#How many did Mikael and Ifeoma disagree on? MED

final %>%
  mutate(Disagreements = case_when(Disagreements %in% c("diasagreement", "disagreemet", "disagrement", "disasgreement") ~ "disagreement",
                                   Disagreements == "X" ~ "consensus found",
                                   TRUE ~ Disagreements)) %>%
  count(Disagreements)

#How many responses fell into two buckets? MED

final %>%
  filter(!is.na(`Final 2nd:`)) %>%
  summarize("Two Buckets" = n())


#Average Disfavorability Score Med vs. Legal

full_full %>%
  summarise(Legal_Disfavorability = mean(Q48B), Medical_Disfavorability = mean(Q44a)) %>%
  gather(Legal_Disfavorability, Medical_Disfavorability, key = "Type", value = "Disfavorability") %>%
  mutate(sd = sd(Disfavorability), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = Type, y = Disfavorability)) +
  geom_col() +
  geom_errorbar(aes(ymin = Disfavorability- se, ymax = Disfavorability + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score Med vs. Legal", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


full_full %>%
  gather(Q44a, Q48B, key = "Type", value = "Disfavorability") %>%
  filter(Disfavorability != -1) %>%
  group_by(Type) %>%
  count(Disfavorability) %>%
  ggplot(aes(x = Disfavorability, y = n, fill = Type)) +
  geom_col(position = "dodge")

```


```{r Med Class}

#Combine classifications conditional mistrust, conditional trust, and need more information into one class.

split_fix <- split %>% 
  mutate(Classification = `Final`) %>%
  mutate(Classification = case_when(Classification %in% c("conditional mistrust", "conditional trust") ~ "need more information", TRUE ~ Classification))


#Frequency of Open-Ended Response Classifications

split_fix %>% 
  ggplot(aes(x = Classification, fill = Classification)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Frequency of Open-Ended Response Classifications")


#Average Disfavorability Score by RESPONSE CLASSIFICATION

split_fix %>%
  filter(Q44a != -1) %>%
  group_by(Classification) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = Classification, y = `Average Favorability`, fill = Classification)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Classification", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")

```
```{r Legal Class}

#Combine classifications conditional mistrust, conditional trust, and need more information into one class.

split_fix_legal <- split_legal %>% 
  mutate(Classification = `Final`) %>%
  mutate(Classification = case_when(Classification %in% c("conditional mistrust", "conditional trust") ~ "need more information", TRUE ~ Classification))


#Frequency of Open-Ended Response Classifications

split_fix_legal %>% 
  ggplot(aes(x = Classification, fill = Classification)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Frequency of Open-Ended Response Classifications")


#Average Disfavorability Score by RESPONSE CLASSIFICATION

split_fix_legal %>%
  filter(Q48B != -1) %>%
  group_by(Classification) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = Classification, y = `Average Favorability`, fill = Classification)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Classification", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")

```
```{r Class Comparison}

split_summ_med <- split_fix %>%
  filter(Q44a != -1) %>%
  group_by(Classification) %>%
  summarise(Med_Favorability = mean(Q44a), sd = sd(Q44a), se = 1.96 * sqrt(n()))

split_summ <- split_fix_legal %>%
  filter(Q48B != -1) %>%
  group_by(Classification) %>%
  summarise(Legal_Favorability = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  full_join(split_summ_med, by = "Classification") %>%
  gather(Med_Favorability, Legal_Favorability, key = "Type", value = "Favorability")

split_summ %>%
  ggplot(aes(x = Classification, y = Favorability, fill = Type)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Classification", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")

```


```{r MED ANALYSIS}

#Average Disfavorability Score by PARTY ID

full_full %>%
  filter(Q44a != -1) %>%
  mutate(partyid7 = case_when(partyid7 == 1 ~ "1 - Strong Republican", 
                           partyid7 == 7 ~ "7 - Strong Democrat",
                           TRUE ~ as.character(partyid7))) %>%
  group_by(partyid7) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = partyid7, y = `Average Favorability`, fill = partyid7)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Party ID", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by POLITICAL IDEOLOGY

full_full %>%
  filter(Q44a != -1, ppp10012 != -1, !is.na(ppp10012)) %>%
  mutate(ppp10012 = case_when(ppp10012 == 1 ~ "1 - Extremely Liberal", 
                           ppp10012 == 7 ~ "7 - Extremely Conservative",
                           TRUE ~ as.character(ppp10012))) %>%
  group_by(ppp10012) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = ppp10012, y = `Average Favorability`, fill = ppp10012)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Political Ideology", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by 2016 VOTING

full_full %>%
  filter(Q44a != -1, pppa1690 %in% c(1, 2)) %>%
  mutate(pppa1690 = case_when(pppa1690 == 1 ~ "Clinton", 
                           pppa1690 == 2 ~ "Trump")) %>%
  group_by(pppa1690) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = pppa1690, y = `Average Favorability`, fill = pppa1690)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Political Ideology", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by HISPANIC STATUS

full_full %>%
  filter(Q44a != -1) %>%
  mutate(XHISPAN = case_when(XHISPAN == 1 ~ "Non-Hispanic", TRUE ~ "Hispanic")) %>%
  group_by(XHISPAN) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = XHISPAN, y = `Average Favorability`, fill = XHISPAN)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Hispanic Status", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by AGE

full_full %>%
  filter(Q44a != -1) %>%
  ggplot(aes(x = PPAGE, y = Q44a)) +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Age", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability") +
  xlab("Age")


#Average Disfavorability Score by AGE GROUP

full_full %>%
  filter(Q44a != -1) %>%
  mutate(ppagecat = case_when(ppagecat == 1 ~ "18-24", 
                           ppagecat == 2 ~ "25-34", 
                           ppagecat == 3 ~ "35-44",
                           ppagecat == 4 ~ "45-54",
                           ppagecat == 5 ~ "55-64",
                           ppagecat == 6 ~ "65-74",
                           ppagecat == 7 ~ "75+")) %>%
  group_by(ppagecat) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = ppagecat, y = `Average Favorability`, fill = ppagecat)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Age Group", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by EDUCATION

full_full %>%
  filter(Q44a != -1) %>%
  mutate(PPEDUCAT = case_when(ppagecat == 1 ~ "Less than high school", 
                           ppagecat == 2 ~ "High school", 
                           ppagecat == 3 ~ "Some college",
                           ppagecat == 4 ~ "Bachelor's degree or higher")) %>%
  group_by(PPEDUCAT) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPEDUCAT, y = `Average Favorability`, fill = PPEDUCAT)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Education", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by GENDER

full_full %>%
  filter(Q44a != -1) %>%
  mutate(PPGENDER = case_when(PPGENDER == 1 ~ "Male", 
                           PPGENDER == 2 ~ "Female")) %>%
  group_by(PPGENDER) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPGENDER, y = `Average Favorability`, fill = PPGENDER)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Gender", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by INCOME

full_full %>%
  filter(Q44a != -1) %>%
  group_by(PPINCIMP) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPINCIMP, y = `Average Favorability`, fill = PPINCIMP)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by INCREASING Income", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank.") +
  ylab("Average Disfavorability")


full_full %>%
  filter(Q44a != -1, race1 != -1) %>%
  mutate(race1 = case_when(race1 == 0 ~ "Nonwhite", 
                           race1 == 1 ~ "While")) %>%
  group_by(race1) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = race1, y = `Average Favorability`, fill = race1)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by INCREASING Income", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank.") +
  ylab("Average Disfavorability")

full_full %>%
  filter(Q44a != -1, race2 != -1) %>%
  mutate(race2 = case_when(race2 == 0 ~ "Non-black", 
                           race2 == 1 ~ "Black")) %>%
  group_by(race2) %>%
  summarise(`Average Favorability` = mean(Q44a), sd = sd(Q44a), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = race2, y = `Average Favorability`, fill = race2)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by INCREASING Income", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank.") +
  ylab("Average Disfavorability")


```

```{r LEGAL ANALYSIS}

#Average Disfavorability Score by PARTY ID

full_full %>%
  filter(Q48B != -1) %>%
  mutate(partyid7 = case_when(partyid7 == 1 ~ "1 - Strong Republican", 
                           partyid7 == 7 ~ "7 - Strong Democrat",
                           TRUE ~ as.character(partyid7))) %>%
  group_by(partyid7) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = partyid7, y = `Average Favorability`, fill = partyid7)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Party ID", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by POLITICAL IDEOLOGY

full_full %>%
  filter(Q48B != -1, ppp10012 != -1, !is.na(ppp10012)) %>%
  mutate(ppp10012 = case_when(ppp10012 == 1 ~ "1 - Extremely Liberal", 
                           ppp10012 == 7 ~ "7 - Extremely Conservative",
                           TRUE ~ as.character(ppp10012))) %>%
  group_by(ppp10012) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = ppp10012, y = `Average Favorability`, fill = ppp10012)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Political Ideology", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by 2016 VOTING

full_full %>%
  filter(Q48B != -1, pppa1690 %in% c(1, 2)) %>%
  mutate(pppa1690 = case_when(pppa1690 == 1 ~ "Clinton", 
                           pppa1690 == 2 ~ "Trump")) %>%
  group_by(pppa1690) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = pppa1690, y = `Average Favorability`, fill = pppa1690)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Political Ideology", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by HISPANIC STATUS

full_full %>%
  filter(Q48B != -1) %>%
  mutate(XHISPAN = case_when(XHISPAN == 1 ~ "Non-Hispanic", TRUE ~ "Hispanic")) %>%
  group_by(XHISPAN) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = XHISPAN, y = `Average Favorability`, fill = XHISPAN)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Hispanic Status", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by AGE

full_full %>%
  filter(Q48B != -1) %>%
  ggplot(aes(x = PPAGE, y = Q48B)) +
  geom_jitter() +
  geom_smooth(method = 'lm') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Age", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability") +
  xlab("Age")


#Average Disfavorability Score by AGE GROUP

full_full %>%
  filter(Q48B != -1) %>%
  mutate(ppagecat = case_when(ppagecat == 1 ~ "18-24", 
                           ppagecat == 2 ~ "25-34", 
                           ppagecat == 3 ~ "35-44",
                           ppagecat == 4 ~ "45-54",
                           ppagecat == 5 ~ "55-64",
                           ppagecat == 6 ~ "65-74",
                           ppagecat == 7 ~ "75+")) %>%
  group_by(ppagecat) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = ppagecat, y = `Average Favorability`, fill = ppagecat)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Age Group", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by EDUCATION

full_full %>%
  filter(Q48B != -1) %>%
  mutate(PPEDUCAT = case_when(ppagecat == 1 ~ "Less than high school", 
                           ppagecat == 2 ~ "High school", 
                           ppagecat == 3 ~ "Some college",
                           ppagecat == 4 ~ "Bachelor's degree or higher")) %>%
  group_by(PPEDUCAT) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPEDUCAT, y = `Average Favorability`, fill = PPEDUCAT)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Education", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by GENDER

full_full %>%
  filter(Q48B != -1) %>%
  mutate(PPGENDER = case_when(PPGENDER == 1 ~ "Male", 
                           PPGENDER == 2 ~ "Female")) %>%
  group_by(PPGENDER) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPGENDER, y = `Average Favorability`, fill = PPGENDER)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by Gender", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank") +
  ylab("Average Disfavorability")


#Average Disfavorability Score by INCOME

full_full %>%
  filter(Q48B != -1) %>%
  group_by(PPINCIMP) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = PPINCIMP, y = `Average Favorability`, fill = PPINCIMP)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by INCREASING Income", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank.") +
  ylab("Average Disfavorability")


full_full %>%
  filter(Q48B != -1, race1 != -1) %>%
  mutate(race1 = case_when(race1 == 0 ~ "Nonwhite", 
                           race1 == 1 ~ "While")) %>%
  group_by(race1) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = race1, y = `Average Favorability`, fill = race1)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by INCREASING Income", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank.") +
  ylab("Average Disfavorability")

full_full %>%
  filter(Q48B != -1, race2 != -1) %>%
  mutate(race2 = case_when(race2 == 0 ~ "Non-black", 
                           race2 == 1 ~ "Black")) %>%
  group_by(race2) %>%
  summarise(`Average Favorability` = mean(Q48B), sd = sd(Q48B), se = 1.96 * sd/sqrt(n())) %>%
  ggplot(aes(x = race2, y = `Average Favorability`, fill = race2)) +
  geom_col() +
  geom_errorbar(aes(ymin = `Average Favorability`- se, ymax = `Average Favorability` + se), width=.2, position=position_dodge(.9)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average Disfavorability Score by INCREASING Income", caption = "Important Note: A higher ordinal value denotes less willingness to contribute to a DNA to a biobank.") +
  ylab("Average Disfavorability")

```
